# Generated by Django 3.2 on 2021-04-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210413_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_allowed_to_exchange',
            field=models.BooleanField(default=True, verbose_name='Дозволити для обміну'),
        ),
    ]
