# Generated by Django 3.2 on 2021-04-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_is_exchanged'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time_create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата внесення книги'),
        ),
    ]
